package ai.portkey.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A tool call generated by the model.
 *
 * @param id the tool call ID
 * @param type always "function"
 * @param function the function name and arguments
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ToolCall(
        String id,
        String type,
        Function function
) {
    /**
     * @param name function name
     * @param arguments JSON string of arguments
     */
    public record Function(String name, String arguments) {}
}
